tmsProviderText = "//a[normalize-space()='Transaction Management System - Provider']"
patientStatusDownSVG = "//label[normalize-space()='Patient Status']/parent::div//*[name()='svg']"
patientStatusInput = "//label[normalize-space()='Patient Status']/parent::div//input[@spellcheck]"
searchIcon = "//span[@class='icon']"
searchBox = "//input[@placeholder='Search']"
treatmentSVG = "//h4[normalize-space()='Treatment']/following-sibling::img"
homeSVG = "//p[contains(text(),'Home')]/preceding-sibling::*[name()='svg']"
backSVG = "//p[contains(text(),'Back')]/preceding-sibling::*[name()='svg']"
yourHospitalDashboard = "//span[normalize-space()='Your Hospital Dashboard']"
self_vs_entity_toggle_xp = '//*[@id="toggleStatus1"]'
treatmentPlanButton = "//span[contains(text(),'Treatment Plan')]/parent::button"
treatment_plan_for_query = "//span[contains(text(),'Treatment Details')]/parent::button"
initiateEnhancement = "//button[normalize-space()='Initiate Enhancement']"
treatPlanOfEnhancement = "//div[contains(text(),'Treatment Plan')]/parent::div//parent::div//button[@type]"
specialityEnhancement = "//div[div[label[normalize-space()='Speciality:']]]//input[@spellcheck]"
diagnosisEnhancement = "//div[div[label[normalize-space()='Procedure:']]]//input[@spellcheck]"
stratificationEnhancement = "//div[div[label[normalize-space()='Stratification:']]]//input[@spellcheck]"
daysForEnhancement = "//div[div[label[normalize-space()='No. of Days/Units:']]]//input"
enhancementReason = "//div[div[label[normalize-space()='Enhancement Reason:']]]//input[@spellcheck]"
enhancementFileButton = "//input[contains(@type,'file')]"
uploadPlusButton = "//div[div[label[normalize-space()='Enhancement Reason:']]]//img[@class and not(@width)]"
investigationForEnhancementButton = "//div[contains(text(),'Investigations')]/parent::div//parent::div//button[@type]"
addBedSidePhotoForEnhancementButton = "//button[normalize-space()='Add Bed Side Photo']"
uploadInvestigationDocsEnhance = "//label[normalize-space()='Upload Attachment']/following-sibling::div//input"
uploadAddButtonEnhance = "//button[contains(@data-toggle,'collapse')][normalize-space()='ADD']"
addOtherDocumentButton = "//button[normalize-space()='Add Other Documents']"
addOtherDocsInput = "//input[@id='otherInvest']"
validateAndPreview = "//button[normalize-space()='VALIDATE & PREVIEW']"
submitEnhancement = "//button[normalize-space()='SUBMIT ENHANCEMENT']"
submitYesEnhancementButton = "//label[normalize-space()='Are you sure want to submit?']/ancestor::div[@class='modal-content']//button[normalize-space()='YES']"
mainTreatment = "//h4[normalize-space()='Treatment']/parent::button"
showMoreText = "//span[contains(text(),'Show More')]"
showMoreText_first = "(//span[contains(text(),'Show More')])[1]"
show_more_third = "//*[name()='circle' and @id='bg-icon']/ancestor::something/parent::div/parent::div/parent::div/div[2]/div[last()]/div[2]/div[3]//span[contains(text(),'...Show More')]"
showLessTextAlongText = "//span[contains(text(),'Show Less')]//parent::p"
specialityMain = "//span[contains(text(),'Show Less')]/ancestor::tr/td[2]"
commonProceedArrowForSubmission = "//*[name()='path' and @id='Path_98789']"
amountToClaim = "//p[contains(text(),'Total payable amount (after incentives)')]/parent::div/following-sibling::div/p"
billAmountInput = "//input[@id='Hospital Bill Amount']"
saveButton = "//button[normalize-space()='SAVE']"
previewAndClaimButton = "//button[normalize-space()='Preview & Claim' and not(@disabled)]"
submitClaimButton = "//button[normalize-space()='SUBMIT CLAIM']"
registrationNumber = "//span[normalize-space()='Registration ID']/parent::div/following-sibling::div"
rowsPerPageSelect = "//p[text()='Rows per page']/select"
underTreatmentWith_ = "//div[contains(text(),'Under Treatment (')]"
# underTreatmentOnly = "//div[contains(text(),'Under Treatment')]"
underTreatmentOnly = "//*[name()='g' and @id='Group_82319']"
PreauthorizationQueried_With = "//div[contains(text(),'Preauthorization Queried (')]"
ClaimsQueried_With = "//div[contains(text(),'Claims Queried (')]"
viewMoreButton = "//button[text()='View More']"
# PreauthorizationQueriedOnly = "//div[contains(text(),'Preauthorization Queried')]"
PreauthorizationQueriedOnly = "//*[name()='g' and @id='Group_82329']"
# ClaimsQueriedOnly = "//div[contains(text(),'Claims Queried')]"
ClaimsQueriedOnly = "//*[name()='g' and @id='Group_82277']"
loading_for_registration_ids = "//p[contains(text(),'Registration ID:')]"
current_status_xp = "//a[normalize-space()='Home']/ancestor::ol//li[2]"
card_xp = "//div[text()=' ID']/following-sibling::div"
name_xp = "(//img[@alt='image']/parent::div/following-sibling::div/div)[1]"
date_xp = "//div[text()='Registration Date']/following-sibling::div"
amount_query_xp = "//div[p[normalize-space()='Total payable amount (after incentives) :']]/following-sibling::div/p"
depart_xp = "//span[contains(text(),'Show Less')]/parent::p/parent::td/preceding-sibling::td[1]"
depart_xp_claim_q_treatment = "//span[contains(text(),'Show Less')]/parent::p/parent::td/preceding-sibling::td[2]"
depart_xp_claim_q_only = "//span[contains(text(),'Show Less')]/parent::p/parent::div/parent::div/preceding-sibling::div/div"
procedure_xp = "//span[contains(text(),'Show Less')]/parent::p"
finance_close_xp = "//h4[normalize-space()='Finance']/parent::button"
amount_treatment_xp ="//div[normalize-space()='Total Preauth Approved Amount']/following-sibling::div"
last_query_question_xp = "//*[name()='circle' and @id='bg-icon']/ancestor::something/parent::div/parent::div/parent::div/div[2]/div[last()]/div[2]/div[3]"
recent_query_date_xp = "//*[name()='circle' and @id='bg-icon']/ancestor::something/parent::div/parent::div/parent::div/div[2]/div[last()]/div[2]/div[4]"
close_cross_xp = "//*[name()='path' and @id='cross-icon']"



JSON_FILE_PATH = f"..\\async_tms_new\\download\\file_json.json"
RESULT_DATA_JSON = f"..\\async_tms_new\\download\\result_data_json.json"
EXCEL_FILE_PATH = f"..\\async_tms_new\\download\\AYUSHMAN REGISTRATION 2025.xlsx"
