
tmsProviderText = "//a[normalize-space()='Transaction Management System - Provider']"
patientStatusDownSVG = "//label[normalize-space()='Patient Status']/parent::div//*[name()='svg']"
patientStatusInput = "//label[normalize-space()='Patient Status']/parent::div//input[@spellcheck]"
searchIcon = "//span[@class='icon']"
searchBox = "//input[@placeholder='Search']"
treatmentSVG = "//h4[normalize-space()='Treatment']/following-sibling::img"
homeSVG = "//p[contains(text(),'Home')]/preceding-sibling::*[name()='svg']"
backSVG = "//p[contains(text(),'Back')]/preceding-sibling::*[name()='svg']"
yourHospitalDashboard = "//span[normalize-space()='Your Hospital Dashboard']"
treatmentPlanButton = "//span[contains(text(),'Treatment Plan')]/parent::button"
initiateEnhancement = "//button[normalize-space()='Initiate Enhancement']"
treatPlanOfEnhancement = "//div[contains(text(),'Treatment Plan')]/parent::div//parent::div//button[@type]"
specialityEnhancement = "//div[div[label[normalize-space()='Speciality:']]]//input[@spellcheck]"
diagnosisEnhancement = "//div[div[label[normalize-space()='Procedure:']]]//input[@spellcheck]"
stratificationEnhancement = "//div[div[label[normalize-space()='Stratification:']]]//input[@spellcheck]"
daysForEnhancement = "//div[div[label[normalize-space()='No. of Days/Units:']]]//input"
enhancementReason = "//div[div[label[normalize-space()='Enhancement Reason:']]]//input[@spellcheck]"
enhancementFileButton = "//input[contains(@type,'file')]"
uploadPlusButton = "//div[div[label[normalize-space()='Enhancement Reason:']]]//img[@class and not(@width)]"
investigationForEnhancementButton = "//div[contains(text(),'Investigations')]/parent::div//parent::div//button[@type]"
addBedSidePhotoForEnhancementButton = "//button[normalize-space()='Add Bed Side Photo']"
uploadInvestigationDocsEnhance = "//label[normalize-space()='Upload Attachment']/following-sibling::div//input"
uploadAddButtonEnhance = "//button[contains(@data-toggle,'collapse')][normalize-space()='ADD']"
addOtherDocumentButton = "//button[normalize-space()='Add Other Documents']"
addOtherDocsInput = "//input[@id='otherInvest']"
validateAndPreview = "//button[normalize-space()='VALIDATE & PREVIEW']"
submitEnhancement = "//button[normalize-space()='SUBMIT ENHANCEMENT']"
submitYesEnhancementButton = "//label[normalize-space()='Are you sure want to submit?']/ancestor::div[@class='modal-content']//button[normalize-space()='YES']"
mainTreatment = "//h4[normalize-space()='Treatment']/parent::button"
showMoreText = "//span[contains(text(),'Show More')]"
showLessTextAlongText = "//span[contains(text(),'Show Less')]//parent::p"
specialityMain = "//span[contains(text(),'Show Less')]/ancestor::tr/td[2]"
commonProceedArrowForSubmission = "//*[name()='path' and @id='Path_98789']"
amountToClaim = "//p[contains(text(),'Total payable amount (after incentives)')]/parent::div/following-sibling::div/p"
billAmountInput = "//input[@id='Hospital Bill Amount']"
saveButton = "//button[normalize-space()='SAVE']"
previewAndClaimButton = "//button[normalize-space()='Preview & Claim' and not(@disabled)]"
submitClaimButton = "//button[normalize-space()='SUBMIT CLAIM']"
registrationNumber = "//span[normalize-space()='Registration ID']/parent::div/following-sibling::div"
rowsPerPageSelect = "//p[text()='Rows per page']/select"
underTreatmentWith = "//div[contains(text(),'Under Treatment (')]"
underTreatmentOnly = "//div[contains(text(),'Under Treatment')]"
PreauthorizationQueried = "//div[contains(text(),'Preauthorization Queried (')]"
ClaimsQueried = "//div[contains(text(),'Claims Queried (')]"
viewMoreButton = "//button[text()='View More']"
PreauthorizationQueriedOnly = "//div[contains(text(),'Preauthorization Queried')]"
ClaimsQueriedOnly = "//div[contains(text(),'Claims Queried')]"

