from dkbssy.name_list_generator.name_list_gen_2 import _main


"""
CHANGES REQUIRED BEFORE RUNNING
0 SORT THE INCENTIVE CASES ACCORDING TO DATE, SO THAT NAMES ARE SIMILAR, AVOIDING THE LEAVES OF SOME IN DISCONTINUED SORTING
1 INCENTIVE_NAME_ADDING_WORKBOOK_NAME
2 required_cat_num
3 DEPARTMENT NAME -> Change the incentive_ver_3 -> B5
4 THE DATE IN THE NAME GENERATION SHEET LIKE "EYE 4 1" SHOULD BE IN DATETIME VERSION WITH DDMMYYYY
5 THE ROWS BELOW THE LAST INCENTIVE CASE DATA SHOULD BE DELETED AS THE BLANK ROWS GENERATE THE 'NONE' ERRORS FREQUENTLY. FILTERING 'NONE' IS NOT SUFFICIENT

"""

INCENTIVE_CATEGORY_NUMS = [1, 2, 3, 4, 5, 6, 7, 8, 9]  # Anaesthesia removed if required add '6' with comma ',' sign


DEPARTMENT_FOLDER_PATH = r"G:\My Drive\GdrivePC\Hospital\RSBY\New\Upload Formats\Pedia\PediaMedical"

_main(DEPARTMENT_FOLDER_PATH=DEPARTMENT_FOLDER_PATH, INCENTIVE_CATEGORY_NUMS=INCENTIVE_CATEGORY_NUMS)

