import asyncio
import time

from playwright.async_api import async_playwright
from playwright.sync_api import sync_playwright
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select

from dkbssy.utils.colour_prints import ColourPrint


def dk_via_query(case_number):
    chrome_options = Options()
    chrome_options.debugger_address = "127.0.0.1:9222"

    # No need to set executable_path if chromedriver is in PATH
    driver = webdriver.Chrome(options=chrome_options)

    wait = WebDriverWait(driver, 20)
    # return driver, wait
    def finding_wait_by( xpath):
        return wait.until(EC.presence_of_element_located((By.XPATH, xpath)))

    # driver.get('https://dkbssy.cg.nic.in/secure/login.aspx')
    # # Now driver is connected to the existing Chrome instance
    # username_key = "HOSP22G1466591"
    # pass_key = "Gmc@pmjay1"
    # driver.maximize_window()
    # driver.find_element(By.NAME, "username").clear()
    # driver.find_element(By.NAME, "username").send_keys(username_key)
    # driver.find_element(By.NAME, "password").clear()
    # driver.find_element(By.NAME, "password").send_keys(pass_key)
    # driver.find_element(By.ID, 'txtCaptcha').click()
    # time.sleep(15)  ### SLEEP GIVEN FOR CAPTCHA ENTRY
    # sign_in = driver.find_element(By.NAME, "loginbutton")
    # sign_in.click()

    ColourPrint.print_bg_red('MANUALLY LOGIN APPROVER PAGE')


    # all_split = case_details.split()
    # case_number, amount = all_split[0], all_split[3]

    ColourPrint.print_turquoise("Query Modify")
    # query_modify = f'https://dkbssy.cg.nic.in/secure/incentivemodule/incentivemoduleApViewDME.aspx?ci={case_number}&{amount}'
    query_modify = f'https://dkbssy.cg.nic.in/secure/incentivemodule/incentivemoduleApViewDME.aspx?ci={case_number}'
    print(query_modify)
    driver.get(query_modify)

    # select options
    approve_query_option = driver.find_element(By.NAME, 'ctl00$ContentPlaceHolder1$StatusTxt')
    approve_query_select = Select(approve_query_option)
    approve_query_select.select_by_value('3')
    # writing in text area
    # wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="ctl00_ContentPlaceHolder1_queryText"]'))).send_keys("REINITIATE".upper())
    submit = driver.find_element(By.NAME, 'ctl00$ContentPlaceHolder1$statusSubmit')
    submit.click()
    time.sleep(1)
    # waiting for pop-up
    wait.until(EC.presence_of_element_located((By.XPATH,'//div[normalize-space()="Query Generated by Approver"]')))
    # waiting for OK dialog
    wait.until(EC.presence_of_element_located((By.XPATH, "/html/body/div[3]/div/div[3]/div/button"))).click()


# dk_approver_login()
# dk_via_query('CASE/PS6/HOSP22G146659/CK7111315	Neurosurgery	Severe	2655.4	28-10-2023	Bansilal')


def dk_play2(case_number):

    play = sync_playwright().start()
    browser = play.chromium.connect_over_cdp('http://localhost:9222')

    context = browser.contexts[0]
    page = context.pages[0]

    new_page = context.new_page()
    new_page.set_default_timeout(5000)

    ColourPrint.print_bg_red('MANUALLY LOGIN APPROVER PAGE')

    ColourPrint.print_turquoise("Query Modify")
    # query_modify = f'https://dkbssy.cg.nic.in/secure/incentivemodule/incentivemoduleApViewDME.aspx?ci={case_number}&{amount}'
    query_modify = f'https://dkbssy.cg.nic.in/secure/incentivemodule/incentivemoduleApViewDME.aspx?ci={case_number}'
    print(query_modify)

    new_page.goto(query_modify)
    # selecting Query
    new_page.select_option('//*[@id="ctl00_ContentPlaceHolder1_StatusTxt"]','3')
    # Filling the text area
    new_page.wait_for_selector('//*[@id="ctl00_ContentPlaceHolder1_queryText"]').fill('REINITIATE')
    # Clicking the SUBMIT
    new_page.wait_for_selector('//*[@id="ctl00_ContentPlaceHolder1_statusSubmit"]').click()
    # Clicking the pop-up
    new_page.wait_for_selector('//div[@class="swal-text"]/following-sibling::div//button').click()
    new_page.close()
    print('Closed approver page')

def dk_play_async(case_number):
    asyncio.run(_dk_play2(case_number))

async def _dk_play2(case_number):
    play = await async_playwright().start()
    browser = await play.chromium.connect_over_cdp('http://localhost:9223')
    context = browser.contexts[0]
    new_page = await context.new_page()

    url = f"https://dkbssy.cg.nic.in/secure/incentivemodule/incentivemoduleApViewDME.aspx?ci={case_number}"
    await new_page.goto(url)

    await new_page.select_option('#ctl00_ContentPlaceHolder1_StatusTxt', '3')
    await new_page.fill('#ctl00_ContentPlaceHolder1_queryText', 'REINITIATE')
    await new_page.click('#ctl00_ContentPlaceHolder1_statusSubmit')
    await new_page.click('//div[@class="swal-text"]/following-sibling::div//button')
    ColourPrint.print_green("Inside Async")
    await new_page.close()
    await play.stop()
    ColourPrint.print_green('Async done')

def dk_play_async_submit(case_number):
    asyncio.run(_resubmit(case_number))

async def _resubmit(case_number):
    play = await async_playwright().start()
    browser = await play.chromium.connect_over_cdp('http://localhost:9222')
    context = browser.contexts[0]
    page = await context.new_page()
    page.set_default_timeout(300000)
    print('Original Site - Here in reinitiate')
    await page.goto(f'https://dkbssy.cg.nic.in/secure/incentivemodule/incentivemoduleQuerryViewDME_Edit.aspx?ci={case_number}')

    # Set up handler before the alert appears
    page.on("dialog", lambda dialog: dialog.accept())

    await page.locator('//*[@id="ctl00_ContentPlaceHolder1_button_submit"]').click()  # trigger alert

    await page.wait_for_selector("//button[normalize-space()='OK']", timeout=120000)  # wait for OK button
    await page.close()
    await play.stop()

def dk_play_async_download_setup(port, download_dir):
    asyncio.run(dk_play_async_download_setup(download_dir))

async def _download_set_up(port, download_dir):
    play = await async_playwright().start()
    browser = await play.chromium.connect_over_cdp(f'http://localhost:{port}')
    # Use an isolated context with download path
    context = await browser.new_context(accept_downloads=True, downloads_path=download_dir)
    page = await context.new_page()
    ColourPrint.print_blue("Downloading the Incentive Initiated Cases")
    await page.close()
    await play.stop()